version: '3.8'

services:
    frontend:
        image: bblueberries/jaroonsin:v1.0
        restart: always
        env_file:
            - .env
        ports:
            - '3000:3000'
        networks:
            - leaseease-network
    backend:
        image: kanpasit/leaseease-backend:latest
        restart: always
        env_file:
            - .env
        ports:
            - '8080:8080'
        networks:
            - leaseease-network

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup
        restart: always
        networks:
            - leaseease-network

networks:
    leaseease-network:
        driver: bridge
